name: Update Profile README

on:
  schedule:
    # Roda todos os dias às 00:00 (Meia-noite UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite que você clique em "Run workflow" manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Apenas o commit mais recente

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Aggregator Script
        env:
          # Os tokens virão dos Secrets do seu repositório
          ITCHIO_TOKEN: ${{ secrets.ITCHIO_TOKEN }}
          NEXUSMODS_TOKEN: ${{ secrets.NEXUSMODS_TOKEN }}
        run: python update_profile.py

      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add README.md
          
          # Apenas commita se houver alterações no README
          git diff --quiet && git diff --staged --quiet || git commit -m "Automated Profile Update [skip ci]"
          git push
